version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    env_file:
      - ./server/.env
      - ./.release.env # <-- so /api/health can show COMMIT
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://127.0.0.1:3000/api/category/list || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 10s

  frontend:
    build:
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
